### ISSUE TITLE
[Feature Request] Style the turn on/turn off the lights button

### ISSUE THREAD

**Issue by harshhhdev** [harshhhdev/app-idea-generator#12]
**Is your feature request related to a problem? Please describe.**
There's just some text on the screen for now, doesn't look too good.

**Describe the solution you'd like**
Add an icon or style the button. 

**Describe alternatives you've considered**
A font awesome icon instead of some text.

**Comment by lakshyatyagi24** [comment]
Please assign this issue to me

**Comment by harshhhdev** [comment]
Sorry. Just notices another persons PR for this. If I don't like it, then I'll assign it to you.

**Comment by harshhhdev** [comment]
I'll assign it to you. Wasn't really a fan of the changes the person made.

**Comment by lakshyatyagi24** [comment]
Ok i am working on it

**Comment by harshhhdev** [comment]
I'm really sorry, I was running the previous version of the file, not the one he sent me.

I merged his PR in with this, because I was a fan of the changes.

Sorry for all the inconvenience, I'd be glad to add assign you another feature though.
