### ISSUE TITLE
[Feature Request] Save lightmode and darkmode settings.

### ISSUE THREAD

**Issue by harshhhdev** [harshhhdev/app-idea-generator#15]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I refresh the page, my dark mode preference is not saved.

**Describe the solution you'd like**
Save the setting in local storage.

**Describe alternatives you've considered**
N/A

**Comment by thauska** [comment]
Can I handle this?

**Comment by TiagoSansao** [comment]
I can do it.

**Comment by TiagoSansao** [comment]
Hi, I finished. #16 

Good luck with your project ^^

**Comment by harshhhdev** [comment]
@thauska sorry I could not get to your pull request earlier. @TiagoSansao has already made a pull request for it, which I have tested out.
